export enum AUTHENTICATOR_TYPES {
    GOOGLE_OAUTH2 = 'GOOGLE_OAUTH2',
    CLIENT = 'CLIENT',
}

export const AUTHENTICATION_BASE_ENDPOINT = `/authentication`;

export const AUTHENTICATION_ENDPOINT = `${AUTHENTICATION_BASE_ENDPOINT}/authenticate`;

export const VERIFICATION_ENDPOINT = `${AUTHENTICATION_BASE_ENDPOINT}/verify`;

export const VALIDATION_ENDPOINT = `${AUTHENTICATION_BASE_ENDPOINT}/validate`;
