name: PR Tests

on:
    pull_request:
        branches:
            - master

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3
            - uses: ./.github/workflows/setup
            - run: pnpm lint

    e2e:
        needs: [lint]
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                os: [macos-latest, ubuntu-latest, windows-latest]

        steps:
            - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3
            - uses: ./.github/workflows/setup
            - uses: actions/cache@a7c34adf76222e77931dedbf4a45b2e4648ced19 # tag=v3
              if: ${{ !env.ACT }}
              id: relate-e2e-cache
              with:
                  path: 'e2e/relate fixtures/cache/dbmss'
                  key: relate-e2e-${{ runner.os }}
            - run: pnpm test
