name: PR Tests

on:
    pull_request:
        branches:
            - master

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3
            - uses: ./.github/workflows/setup
            - run: pnpm lint

    e2e:
        needs: [lint]
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                os: [macos-latest, ubuntu-latest, windows-latest]

        steps:
            - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3
            - uses: ./.github/workflows/setup
            - run: pnpm test
