name: Release

on:
    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
    e2e:
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                os: [macos-latest, ubuntu-latest, windows-latest]

        steps:
            - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3
            - uses: ./.github/workflows/setup
            - run: pnpm test

    release:
        needs: [e2e]
        name: Release
        runs-on: ubuntu-latest
        environment: release
        steps:
            - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3
            - uses: ./.github/workflows/setup

            - name: Bump versions
              run: pnpm changeset version

            - name: Update docs
              run: pnpm generate:docs

            # Commit only if changes actually exist
            # https://stackoverflow.com/a/40255467/3247715
            - name: Configuring github user and commit changes from CI
              run: |
                  git config user.name "${{ github.actor }}"
                  git config user.email "${{ github.actor}}@users.noreply.github.com"
                  git add .
                  git diff --quiet && git diff --staged --quiet || git commit -m "Publish"
                  git log -3
                  git show --name-only

            - name: Setup npmrc
              run: echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}' >> .npmrc

            - name: Publish NPM packages
              run: pnpm changeset publish
              env:
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Reset npmrc
              run: git restore .npmrc

            - name: Push commit and tags
              run: git push --follow-tags
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
