name: Release

on:
    push:
        branches:
            - master

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
    e2e:
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                os: [macos-latest, ubuntu-latest, windows-latest]

        steps:
            - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3
            - uses: ./.github/workflows/setup
            - run: pnpm test

    release:
        needs: [e2e]
        name: Release
        runs-on: ubuntu-latest
        environment: release
        permissions:
            contents: write
            pull-requests: write
        steps:
            - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3
            - uses: ./.github/workflows/setup

            # Create a pull request with all of the package versions and
            # changelogs updated and when there are new changesets on master,
            # the PR will be updated. When the PR is merged the packages are
            # published to NPM automatically.
            - name: Create Release Pull Request or Publish to npm
              id: changesets
              uses: changesets/action@v1
              with:
                  version: pnpm run version
                  publish: pnpm changeset publish
              env:
                  GITHUB_TOKEN: ${{ secrets.GH_PAT_PULL_REQUEST }}
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
